spring:
  datasource:
    # MariaDB (Backup)
    # url: jdbc:mariadb://localhost:3306/snipp_link?allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true
    # username: hong
    # password: ENC(QOV4BYBY1WUIO0hm0uON4l4KqO8EgLkXDBkCbMisSE7/J3VKfs0DdeDxej21dC5o)
    # driver-class-name: org.mariadb.jdbc.Driver

    # H2
    url: jdbc:h2:mem:snipp_link;MODE=MariaDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    # allow-multi-query: true # Removed: Configured directly in URL if needed
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

hong:
  short-url:
    secret-key: ENC(y1vnk0wEj21ZWHvsNs5PBS205F6TA98LcopBnfWPcFqkpp1fBOYZL6ILqh5zldH0kth2rHmhC/52C6EuEDnmxg==)
  base-url: 'http://localhost:8083'
  ckeditor:
    path: D:/hongFileDir/snipp_link/
    start-path: "/ckImage/"
    pattern: "/ckImage/**"

jasypt:
  encryptor:
    bean: 'snippLinkEncryptor'
    password: ${JASYPT_PASSWORD}